### ISSUE TITLE
[Request] Condition Lab & Triggler 

### ISSUE THREAD

**Issue by BenNelsonNeb** [TheGiddyLimit/plutonium-addon-automation#100]
I know DFred's Convenient Effects is somewhat popular but I cannot stand it. Wonder if compatibility for Condition Lab & Triggler modules could be added as an alternate for effects.

**Comment by TheGiddyLimit** [comment]
using "global Forge installs" as the closest available analogue for usage (numbers across _all game systems_, not just dnd5e)

DFred's Convenient Effects:

![dfc](https://img.shields.io/badge/dynamic/json?label=Forge%20Installs&query=package.installs&suffix=%25&url=https%3A%2F%2Fforge-vtt.com%2Fapi%2Fbazaar%2Fpackage%2Fdfreds-convenient-effects&colorB=4aa94a)

Condition Lab & Triggler:

![clt](https://img.shields.io/badge/dynamic/json?label=Forge%20Installs&query=package.installs&suffix=%25&url=https%3A%2F%2Fforge-vtt.com%2Fapi%2Fbazaar%2Fpackage%2Fcondition-lab-triggler&colorB=4aa94a)

so I think it's fair to say the community favours DFred's offerings, at the moment.

Generally, this module aims to keep optionality to a bare minimum, as every option added exponentially increases the number of things which need tested, maintained, and are at risk of exploding. Allowing the user to swap out the conditions implementation, a fundamental component, goes against this. It's a "no" for now, I'm afraid.
