### ISSUE TITLE
[Feature Request] Condition Lab & Triggler alternate

### ISSUE THREAD

**Issue by BenNelsonNeb** [TheGiddyLimit/plutonium-addon-automation#101]
I might be in the minority, but DFRED Convenient Effects is not my favorite module.  Tried using it multiple times but Condition Lab & Triggler always seems to win. Is it possible to have Condition Lab as an alternate to DFreds?

**Comment by revilowaldow** [comment]
See the response on your last issue.

https://github.com/TheGiddyLimit/plutonium-addon-automation/issues/100#issuecomment-1766691569
