### ISSUE TITLE
Shield Equipment of Monsters gets confused with Shield Spell by CPR 

### ISSUE THREAD

**Issue by stschmitt87** [TheGiddyLimit/plutonium-addon-automation#102]
When importing creatures that wear a shield (equipment), e.g. Hobgoblin, that shield gets a reaction that increases AC and makes you immune to Magic Missile, like the Shield spell. 

This only happens when Automation and Chris' Premades modules are active, and the "Enable Integration with Chris' Premades" option is enabled. 

![image](https://github.com/TheGiddyLimit/plutonium-addon-automation/assets/52425547/c6e2f693-6227-4031-9dc7-a17e6d74ca9d)

**Comment by TheGiddyLimit** [comment]
ty, fixed with combined 0.7.3 + next Plutonium release (pending)
