### ISSUE TITLE
Prompt for required module-dependency configuration

### ISSUE THREAD

**Issue by Spappz** [TheGiddyLimit/plutonium-addon-automation#17]
There are at least some settings in Midi QoL and DFCE that *must* be set a certain way or the automation won't work. We need a way to verify this on world load and, if not configured correctly, display a pop-up to GMs asking for it to be changed.

Template:
> Plutonium Addon: Data requires Midi QoL and DFred's Convenient Effects to be configured in a particular way:
> - list of settings
> - that need to be changed
> - dynamically render only what needs to be changed if the list ends up being long
> 
> If you don't configure these settings, Plutonium Addon: Data will likely not work as intended.
>
> **Auto-configure settings** | **Close** | **Don't ask me again**

If the pop-up isn't feasible, then simply exposing the settings on the README would technically be sufficient.

First step is to work out what we need; we can tackle the pop-up (if feasible) afterwards.

**Comment by Spappz** [comment]
`Midi-QoL > Config > Workflow > Apply Convenient Effects` needs to be set to `Apply Item effects, if absent apply CE`.

From Midi QoL's README:
> If you have installed itemmacro please make sure you disable the ItemMacro config settings:
> - "character sheet hook" else when you use the item the macro will get called bypassing midi-qol/dae completely and none of the arguments will get populated.
> - "override default macro execution"  If this is enabled the hotbar hooks will directly call the item macro and won't work as expected for dae/midi.
> The settings are per player so each player needs to change the setting to disabled.

Last line looks... false? At least according to [DF Settings Clarity](https://foundryvtt.com/packages/df-settings-clarity/).
![image](https://user-images.githubusercontent.com/34202141/168449417-9a405119-37e6-4e33-9aa2-3a6c4f4705aa.png)

**Comment by TheGiddyLimit** [comment]
`DFreds Convenient Effects > Modify Status Effects` needs to be set to `Replace` or `Add`

i.e.:

![image](https://user-images.githubusercontent.com/25264887/184940571-938a343d-599a-4767-8b55-34e2f9f72d98.png)

Without the CE config, Midi doesn't let you set CE effects using `Status Effect`, from what I can see 🤔 Automatically generating these effects seems like a good idea?

**Comment by Spappz** [comment]
You can use `macro.CE` to force a CE, but the DAE README mentions to use `statusEffect` preferentially (no reason really given, though; see below). Honestly, if you're gonna use DFCE for automation... why wouldn't you register them to status effects?

![image](https://user-images.githubusercontent.com/34202141/185007174-06b42489-1550-4bd4-b50f-3d4ffb1ae7d3.png)

I would prefer using DFCE where possible because it's generally useful (i.e. saves us writing) and supposedly has some 'extra' compatibility with Midi. Yes, it's absolutely possible that we simply steal what DFCE has and hardcode it to each item individually, but that's a bad idea because bloat and things like 'advantage on saves to resist being charmed' or 'immune to stunned' won't automate nicely.

As for the that setting, I'll just include it in the list of required settings on the README (see #33).
