### ISSUE TITLE
Determine core module dependencies

### ISSUE THREAD

**Issue by Spappz** [TheGiddyLimit/plutonium-addon-automation#18]
Current list:
- Plutonium (lmao)
- DAE
- Midi QoL
- DFred's Convenient Effects
- times-up

Item Macro is technically not needed since its data is stored in flags regardless, and other modules can access it. Details on this and 'ecosystem' modules like about-time can be exposed in the README.

'Rarely used' modules such as Active Auras and Better Curses are handled on a per-item basis, but they can still be listed in the README.

If there's any more to be made, now's the time to say it!

**Comment by jbowensii** [comment]
ItemMacro

**Comment by jbowensii** [comment]
Active Auras is another module commonly used ...

**Comment by Spappz** [comment]
> ItemMacro

We don't actually _need_ ItemMacro as a dependency; Midi-QoL can execute the macro whether or not the module is enabled. The only reason to have the module enabled is to read/edit the macro... which users probably shouldn't be doing. So, ItemMacro isn't actually a module dependency, it's just a secret tool we use 😏

> Active Auras

In the data there's a `required` array for each item, which lists any _additional_ modules that are required to run the automation. Active Auras was basically the reason for this: yes, it's hugely useful when it's needed, but there is probably several cases where you'd _never_ need it (e.g. my campaign right now!). So, no need for the computational overhead.

This issue is basically to list the module dependencies we will force everyone to activate in _all_ cases. Honestly, I feel like it's 100% complete now, but I'd like to confirm before forgetting...

---

Do we need Advanced Macros? I can't remember if that's a dependency of anything else, but I feel it's important for our Item Macro wrangling.

**Comment by Spappz** [comment]
> Do we need [Advanced Macros](https://github.com/League-of-Foundry-Developers/fvtt-advanced-macros/)?

No.
![Screenshot 2022-05-30 at 16 13 06](https://user-images.githubusercontent.com/34202141/171021005-10e18a40-d8a1-4c0e-9ed2-6ca0147f8cd0.png)
