### ISSUE TITLE
Automated releases

### ISSUE THREAD

**Issue by Spappz** [TheGiddyLimit/plutonium-addon-automation#23]
Requiring:
- Version bump script
- `manifest` and `download` links in `module.json`

**Comment by TheGiddyLimit** [comment]
Releases working; https://github.com/TheGiddyLimit/plutonium-addon-automation/releases

No need for a version bump script, `npm version <major|minor|patch>` will do us just fine. I _think_ a build will fail, currently, if you forget to bump before merging a PR to `master`, as it'll try to create a release with the same name as the last one, and fall over. Might be misremembering though! Just don't forget to bump the version, tbh!
