### ISSUE TITLE
Security, Vandalism and Review Process

### ISSUE THREAD

**Issue by revilowaldow** [TheGiddyLimit/plutonium-addon-automation#27]
Typically the current homebrew repository is quite light touch on actual review of content.
If we're going to be accepting macros and therefore executed code into this repo I'd like to see a more through verification process to ensure nobody attempts to slip something malicious in through a macro.
There's plenty of opinionated people out there regarding plutonium, and also regarding homebrew content on 5eTools, some of whom might have the bright idea to add "if roll attack, delete entire world" to a macro.

I think this is most easily solved by Giddy being diligent on skim reading any pulls once this project gets going; i.e. reviewing proposed code as code rather than as content? Thoughts?

**Comment by TheGiddyLimit** [comment]
I'm not about to be on the hook for reviewing every scuffed macro that makes its way through here
Sounds like you're volunteering though 🤔

**Comment by jbowensii** [comment]
I think divide and conquer is the way to go, single points of failure will never keep up.

**Comment by revilowaldow** [comment]
> I'm not about to be on the hook for reviewing every scuffed macro 

I was thinking more a cursory check for deliberately malicious code rather than actual verification stuff works

> Sounds like you're volunteering though 🤔

I'd be happy to if I knew javascript :/

**Comment by Spappz** [comment]
For _core_ data, I have intended and alluded to a 'peer review' process where at least one other person gives it a cursory test before merging. For homebrew data... yeah, I'm more inclined to just flag a huge warning and let them deal with it themselves. _I_ don't want to be on the hook for problems either, and I also certainly don't want to be reviewing every single macro.

I'm fine with giving _extremely_ brief checks (i.e. flick through to make sure the macro isn't suspiciously large and doesn't redirect to any other website), but, yeah, ultimately it's the same as 5eT homebrew containing a `<script>bitcoin.miner.startProess()</script>` in its `entries`.

**Comment by Spappz** [comment]
Since the macros are now split out into actual JS files, would it be possible to have some automated script check that, at the very least, no macro is:
- Connecting to the internet
- Accessing the local filesystem
- Really doing anything that isn't either 100% private in scope or via the Foundry API

I'm assuming there's ways around it but perhaps some small protection is better than none at all?

**Comment by TheGiddyLimit** [comment]
> some small protection is better than none at all?

Anything I might write would be laughably incomplete, or an infinite timesink, neither of which is very appealing. So, installing a random antivirus lib and having it run over the folder might be the best route?

e.g.:

- https://www.npmjs.com/package/clamscan
- https://www.npmjs.com/package/metadefender

It's going to be bulky and horrible, though. Macros should really be small and human-readable enough that a 30-second scrub through by a human reviewer ought to accomplish the same thing?

**Comment by Spappz** [comment]
> Macros should really be small and human-readable enough that a 30-second scrub through by a human reviewer ought to accomplish the same thing

I agree completely on the 'small and human-readable' part, it's just that I really don't care for proofreading several thousand lines of JS *even if* each macro itself is small and human-readable! I think my previous "no guarantee provided" stance honestly still stands regardless.

> installing a random antivirus lib and having it run over the folder might be the best route

Didn't consider that, so yes. If you think it's a waste of time, I fall back to the "no guarantee provided" with a minute amount of clicking on the 'Files Changed' on each PR to see if anything screams 'dodgy' 😏

**Comment by TheGiddyLimit** [comment]
yeah frick AV. Like any open-source project, we will go with "well, the code's right there, you could've read it..."
