### ISSUE TITLE
Switch to (at least) JSON schema spec Draft 2019-09 and utilize `unevaluatedProperties`

### ISSUE THREAD

**Issue by TheGiddyLimit** [TheGiddyLimit/plutonium-addon-automation#47]
This will allow us to write tighter schemas, without sacrificing readability.

See:

- https://json-schema.org/understanding-json-schema/reference/object.html#extending-closed-schemas
- https://ajv.js.org/json-schema.html#draft-2019-09  /  https://ajv.js.org/guide/schema-language.html#draft-2019-09-and-draft-2020-12

**Comment by revilowaldow** [comment]
I'd say go to 2019-09 but not to 2020-12 which changes (breaks) the `items` behaviour.
