### ISSUE TITLE
Automatic Dependency Install

### ISSUE THREAD

**Issue by revilowaldow** [TheGiddyLimit/plutonium-addon-automation#60]
If the package management backend addon is installed (do not advise mentioning/documenting this here) in addition to providing a prompt when an import has additional dependencies, also provide a one click option to install and activate that dependency using the backend modification.

This post was paid for by the "well if it's there we might as well use it" gang.

**Comment by TheGiddyLimit** [comment]
While that would be cute, I don't want to:
- give people a reason to install the thing, given that it's a suicidal security hole, or
- spend time implementing/maintaining a feature which only 2 people will ever use, once
depending on whether or not we document it as an option here

**Comment by revilowaldow** [comment]
Sounds fair to me. Just throwing it out there
