### ISSUE TITLE
Slows down Tidy5e Sheet

### ISSUE THREAD

**Issue by DarkSolarLegend** [TheGiddyLimit/plutonium-addon-automation#76]
I was having issues where character sheets were taking 3–5 seconds to open, so I used "Find the Culprit," and it said the culprit was Tidy5e. I thought this was strange, so I ran "Find the Culprit" again but kept Tidy5e and dependency modules like socketlib and libWrapper on, and this time it said that the Plutonium Addon: Automation was the culprit. If I have the addon turned off with all my other modules turned on, Tidy5e character sheets open almost instantly. The opposite is also true: if I have Tidy5e turned off and use the default character sheet with the addon turned on and all my other modules turned on, the character sheets will open just as quickly. It could be one of my other 106 active modules, but from my limited troubleshooting, it seems like the Tidy5e Sheet and the addon don't play well together.

**Comment by TheGiddyLimit** [comment]
yup, this is really a Plutonium bug in disguise, and is fixed there for next release
