### ISSUE TITLE
Consider soft/optional Midi SRD integration

### ISSUE THREAD

**Issue by TheGiddyLimit** [TheGiddyLimit/plutonium-addon-automation#94]
Similar to the work done to make use of Chris' Premades, [Midi SRD](https://foundryvtt.com/packages/midi-srd) potentially has a good set of already-written automations we could pull in.

Also consider when there are "too many" versions of an item available; how best to resolve duplicates/ensure base Plutonium functionality is sensibly overridden when using an available version.

**Comment by revilowaldow** [comment]
Maybe see what libwrapper does in its setting config page for an example of a possible handling preferences page unless an opinionated preference on priority is getting hardcoded

**Comment by TheGiddyLimit** [comment]
Since there's fairly little overlap, it's currently an arbitrary: CPR -> Midi SRD
